export enum Action {
  ADD_RECORD = 'ADD_RECORD',
  DELETE_RECORD = 'DELETE_RECORD',
  UPDATE_RECORD = 'UPDATE_RECORD',
  UPDATE_MONTHLY_RECORDS = 'UPDATE_MONTHLY_RECORDS',
  UPDATE_MONTH = 'UPDATE_MONTH',
}
